# Generated by Django 4.1.3 on 2022-11-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bird', max_length=100)),
                ('family', models.CharField(default='unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BirdImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_image', models.ImageField(upload_to='static_media/images')),
                ('bird', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bird_images', to='static_media.bird')),
            ],
        ),
    ]
