# Generated by Django 4.1.3 on 2022-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
