# Generated by Django 4.1.3 on 2022-11-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_media', '0002_alter_bird_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdimages',
            name='bird',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bird_images', to='static_media.bird'),
        ),
    ]
